info: |-
    Line plots

demo: |-
    clickme("lines")
    data <- 1:10
    cm(data)

scripts:
    - $shared/d3.v3.4.3.js
    - $shared/clickme.js
    - $shared/d3_tip.js

styles:
    - $shared/clickme.css
    - $shared/d3_tip.css
    - $shared/chart.css


require_packages:

require_server: no


